/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as SchedulesRouteImport } from './routes/schedules'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHaWsRouteImport } from './routes/api/ha.ws'
import { Route as ApiCameraEntityRouteImport } from './routes/api/camera.$entity'

const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulesRoute = SchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHaWsRoute = ApiHaWsRouteImport.update({
  id: '/api/ha/ws',
  path: '/api/ha/ws',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCameraEntityRoute = ApiCameraEntityRouteImport.update({
  id: '/api/camera/$entity',
  path: '/api/camera/$entity',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/schedules': typeof SchedulesRoute
  '/statistics': typeof StatisticsRoute
  '/api/camera/$entity': typeof ApiCameraEntityRoute
  '/api/ha/ws': typeof ApiHaWsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/schedules': typeof SchedulesRoute
  '/statistics': typeof StatisticsRoute
  '/api/camera/$entity': typeof ApiCameraEntityRoute
  '/api/ha/ws': typeof ApiHaWsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/schedules': typeof SchedulesRoute
  '/statistics': typeof StatisticsRoute
  '/api/camera/$entity': typeof ApiCameraEntityRoute
  '/api/ha/ws': typeof ApiHaWsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/schedules'
    | '/statistics'
    | '/api/camera/$entity'
    | '/api/ha/ws'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/schedules' | '/statistics' | '/api/camera/$entity' | '/api/ha/ws'
  id:
    | '__root__'
    | '/'
    | '/schedules'
    | '/statistics'
    | '/api/camera/$entity'
    | '/api/ha/ws'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SchedulesRoute: typeof SchedulesRoute
  StatisticsRoute: typeof StatisticsRoute
  ApiCameraEntityRoute: typeof ApiCameraEntityRoute
  ApiHaWsRoute: typeof ApiHaWsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedules': {
      id: '/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof SchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ha/ws': {
      id: '/api/ha/ws'
      path: '/api/ha/ws'
      fullPath: '/api/ha/ws'
      preLoaderRoute: typeof ApiHaWsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/camera/$entity': {
      id: '/api/camera/$entity'
      path: '/api/camera/$entity'
      fullPath: '/api/camera/$entity'
      preLoaderRoute: typeof ApiCameraEntityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SchedulesRoute: SchedulesRoute,
  StatisticsRoute: StatisticsRoute,
  ApiCameraEntityRoute: ApiCameraEntityRoute,
  ApiHaWsRoute: ApiHaWsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
