/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as SchedulesRouteImport } from './routes/schedules'
import { Route as LightsRouteImport } from './routes/lights'
import { Route as ClimateRouteImport } from './routes/climate'
import { Route as CameraRouteImport } from './routes/camera'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCameraEntityRouteImport } from './routes/api/camera.$entity'

const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulesRoute = SchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => rootRouteImport,
} as any)
const LightsRoute = LightsRouteImport.update({
  id: '/lights',
  path: '/lights',
  getParentRoute: () => rootRouteImport,
} as any)
const ClimateRoute = ClimateRouteImport.update({
  id: '/climate',
  path: '/climate',
  getParentRoute: () => rootRouteImport,
} as any)
const CameraRoute = CameraRouteImport.update({
  id: '/camera',
  path: '/camera',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCameraEntityRoute = ApiCameraEntityRouteImport.update({
  id: '/api/camera/$entity',
  path: '/api/camera/$entity',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/camera': typeof CameraRoute
  '/climate': typeof ClimateRoute
  '/lights': typeof LightsRoute
  '/schedules': typeof SchedulesRoute
  '/statistics': typeof StatisticsRoute
  '/api/camera/$entity': typeof ApiCameraEntityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/camera': typeof CameraRoute
  '/climate': typeof ClimateRoute
  '/lights': typeof LightsRoute
  '/schedules': typeof SchedulesRoute
  '/statistics': typeof StatisticsRoute
  '/api/camera/$entity': typeof ApiCameraEntityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/camera': typeof CameraRoute
  '/climate': typeof ClimateRoute
  '/lights': typeof LightsRoute
  '/schedules': typeof SchedulesRoute
  '/statistics': typeof StatisticsRoute
  '/api/camera/$entity': typeof ApiCameraEntityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/camera'
    | '/climate'
    | '/lights'
    | '/schedules'
    | '/statistics'
    | '/api/camera/$entity'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/camera'
    | '/climate'
    | '/lights'
    | '/schedules'
    | '/statistics'
    | '/api/camera/$entity'
  id:
    | '__root__'
    | '/'
    | '/camera'
    | '/climate'
    | '/lights'
    | '/schedules'
    | '/statistics'
    | '/api/camera/$entity'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CameraRoute: typeof CameraRoute
  ClimateRoute: typeof ClimateRoute
  LightsRoute: typeof LightsRoute
  SchedulesRoute: typeof SchedulesRoute
  StatisticsRoute: typeof StatisticsRoute
  ApiCameraEntityRoute: typeof ApiCameraEntityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedules': {
      id: '/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof SchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lights': {
      id: '/lights'
      path: '/lights'
      fullPath: '/lights'
      preLoaderRoute: typeof LightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/climate': {
      id: '/climate'
      path: '/climate'
      fullPath: '/climate'
      preLoaderRoute: typeof ClimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camera': {
      id: '/camera'
      path: '/camera'
      fullPath: '/camera'
      preLoaderRoute: typeof CameraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/camera/$entity': {
      id: '/api/camera/$entity'
      path: '/api/camera/$entity'
      fullPath: '/api/camera/$entity'
      preLoaderRoute: typeof ApiCameraEntityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CameraRoute: CameraRoute,
  ClimateRoute: ClimateRoute,
  LightsRoute: LightsRoute,
  SchedulesRoute: SchedulesRoute,
  StatisticsRoute: StatisticsRoute,
  ApiCameraEntityRoute: ApiCameraEntityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
