/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCameraEntityRouteImport } from './routes/api/camera.$entity'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCameraEntityRoute = ApiCameraEntityRouteImport.update({
  id: '/api/camera/$entity',
  path: '/api/camera/$entity',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/camera/$entity': typeof ApiCameraEntityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/camera/$entity': typeof ApiCameraEntityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/camera/$entity': typeof ApiCameraEntityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/camera/$entity'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/camera/$entity'
  id: '__root__' | '/' | '/api/camera/$entity'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCameraEntityRoute: typeof ApiCameraEntityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/camera/$entity': {
      id: '/api/camera/$entity'
      path: '/api/camera/$entity'
      fullPath: '/api/camera/$entity'
      preLoaderRoute: typeof ApiCameraEntityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCameraEntityRoute: ApiCameraEntityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
